# Site settings

title: Quique Porta
email: contact.13p0l@simplelogin.com
description: >- # this means to ignore newlines until "baseurl:"
  Pagina web de Quique Porta.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.quiqueporta.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: "images/logo.png"
twitter_username: quiqueportac
github_username:  quiqueporta
locale: "en-us"
read_time: true
words_per_minute: 200
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
disqus:
  shortname: "quiqueporta"
# Build settings
# theme: minima
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/default.css"


footer_links:
  - title: Twitter
    url: https://twitter.com/quiqueportac
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/quiqueporta
    icon: fab fa-github-square
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
